name: Output workflow
on: [workflow_dispatch]
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: echo "This project has issues = ${{ github.event.repository.has_issues }}"
